apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
commonLabels:
  myenv: my-pocapp-frontendapp
resources:
#- ns.yaml
- ../../base/
patchesStrategicMerge:
- deployment.yaml
- replica-and-rollout-strategy.yaml
images:
- name: planethomeregistry.azurecr.io/webpoc
  digest: sha256:7641239909e264376ec16288bf9abedeae54577e15e0fd571489fe80c579a832
nameSuffix: -dev
