apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
commonLabels:
  myenv: my-pocapp-frontendapp
resources:
#- ns.yaml
- ../../base/
patchesStrategicMerge:
- deployment.yaml
- replica-and-rollout-strategy.yaml
images:
- name: planethomeregistry.azurecr.io/webpoc
  digest: sha256:60910ba8aba789e8a72133c379c6904a3e9364e679ed7f595fe70983e0a93d52
nameSuffix: -dev
