apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-pocapp
  name: pocapp-svc
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 5000
  selector:
    app: my-pocapp
